{{- if .Values.enableVolumeSnapshot }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bsu-snapshot-controller
  namespace: kube-system
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.snapshot.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
